ALTER TABLE QUESTION
    ADD label varchar NOT NULL DEFAULT 'temporary default label';
ALTER TABLE QUESTION
    ALTER COLUMN label DROP DEFAULT;

ALTER TABLE QUESTION
    ADD COLUMN type varchar(3) NOT NULL DEFAULT 'C';
ALTER TABLE QUESTION
    ALTER COLUMN type DROP DEFAULT;

ALTER TABLE QUESTION
    ADD CONSTRAINT valid_type_cc CHECK (type IN ('OAQ', 'SAQ', 'MAQ'));
